### ISSUE TITLE
не заводится

### ISSUE THREAD

**Issue by ARMrus** [UlianaDzhumok/triple-ocr-server#40]
установлен NVIDIA Container Toolkit
```
version: '4.0'

services:
  ocr-server:
    image: multi-ocr-server:latest
    ports:
      - "8070:9000"
    environment:
      - USE_GPU=true
      - HOST=127.0.0.1
      - PORT=9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: '22'

    user: "1000:1000" 
```
сообщение в логах
      

```
==========

== CUDA ==

==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.

By pulling and using the container, you accept the terms and conditions of this license:

https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Illegal instruction (core dumped)
```
